CREATE TABLE TripProvider (
    StaffID INT AUTO_INCREMENT,
    Name VARCHAR(15) NOT NULL,
	Password VARCHAR(15) NOT NULL,
	Gender VARCHAR(1) NOT NULL,
	DateOfBirth DATE NOT NULL,
    PRIMARY KEY (StaffID)

);